name: label-synchronization
on:
  push:
    branches:
      - main
      - master
    paths:
      - .github/labels.yaml
      - .github/workflows/label-sync.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # write permission is required to edit issue labels
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Synchronize labels
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          dry-run: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-delete: false
          yaml-file: .github/labels.yaml
