# DO NOT CHANGE THIS FILE DIRECTLY
# Source: https://github.com/schubergphilis/mcaf-github-workflows

name: "release-drafter"

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .github/**
      - .gitignore
      - .pre-commit-config.yaml
      - CHANGELOG.md
      - CONTRIBUTING.md
      - LICENSE

permissions:
  # write permission is required to create a github release
  contents: write

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          publish: false
          prerelease: false
          config-name: release-drafter-config.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
